CREATE TABLE STUDENT(RNO INT IDENTITY(1,1),NAMES VARCHAR(20),CLASS VARCHAR(20));

INSERT INTO STUDENT(NAMES,CLASS) VALUES('MANISH','MCA');

SELECT * FROM STUDENT;

CREATE TABLE STUDENTS(RNO INT IDENTITY(1,5),NAMES VARCHAR(20),CLASS VARCHAR(20));

INSERT INTO STUDENTS(NAMES,CLASS) VALUES('GOLU','6TH');

SELECT * FROM STUDENTS;
